version: '3'
services:
  resource_reservation_ui:
    image: resource_reservation_ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    container_name: resource_reservation_ui
    volumes:
       - ./:/app/resource_reservation_ui
